import { Product, Category, Review, Testimonial } from './types';

export type ProductBadge = 'best-seller' | 'new' | 'popular' | 'sale';

export const categories: Category[] = [
  {
    id: 'bundles',
    label: 'Bundles',
    icon: 'Package',
    description: 'Save more with curated product bundles',
    count: 3,
  },
  {
    id: 'accounts',
    label: 'Accounts',
    icon: 'UserCheck',
    description: 'Ready-to-play accounts for FiveM, RedM, Steam, Discord',
    count: 6,
  },
  {
    id: 'menus',
    label: 'Mod Menus',
    icon: 'LayoutGrid',
    description: 'Premium mod menus for FiveM and RedM',
    count: 5,
  },
  {
    id: 'tools',
    label: 'Tools',
    icon: 'Wrench',
    description: 'Executors, spoofers, and bypass tools',
    count: 4,
  },
  {
    id: 'codes',
    label: 'Activation Codes',
    icon: 'Key',
    description: 'Legitimate Rockstar activation codes',
    count: 1,
  },
  {
    id: 'email-accounts',
    label: 'Email Accounts',
    icon: 'Mail',
    description: 'Aged and verified email accounts',
    count: 1,
  },
];

const img = (id: string, seed: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop&_s=${seed}`;

export const products: Product[] = [
  {
    id: '1',
    slug: 'bundle-ham-vanity',
    name: 'Bundle Ham + Vanity',
    category: 'bundles',
    categoryLabel: 'Bundles',
    tagline: 'Get Ham Executor and Vanity Menu together at a discounted price.',
    description:
      'The ultimate modding bundle. Get Ham Executor — a lightweight Lua executor — and Vanity Menu — a premium FiveM modding menu — together and save. Perfect for players who want both power and style.',
    features: [
      'Ham Executor full license',
      'Vanity Menu full license',
      'Save 25% vs buying separately',
      'Lifetime updates for both',
      'Single dashboard download',
      'Priority support',
    ],
    price: 21.99,
    originalPrice: 44.98,
    rating: 4.9,
    reviewCount: 287,
    badge: 'best-seller',
    thumbnail: '/images/products/682550.webp',
    gallery: ['/images/products/682550.webp'],
    techStack: ['C++', 'Lua', 'FiveM'],
    downloads: 8200,
    lastUpdated: '2026-07-12',
    featured: true,
  },
  {
    id: '2',
    slug: 'bundle-ham-cryptic',
    name: 'Bundle Ham + Cryptic',
    category: 'bundles',
    categoryLabel: 'Bundles',
    tagline: 'Ham Executor and Cryptic Menu bundled for maximum value.',
    description:
      'Pair Ham Executor with Cryptic Menu for advanced scripting and deep customization. This bundle gives you both tools at a significant discount, with lifetime updates included.',
    features: [
      'Ham Executor full license',
      'Cryptic Menu full license',
      'Save 25% vs buying separately',
      'Lifetime updates for both',
      'Single dashboard download',
      'Priority support',
    ],
    price: 21.99,
    originalPrice: 43.98,
    rating: 4.8,
    reviewCount: 198,
    badge: 'popular',
    thumbnail: img('1542751370-adc348e3d9aa', 3),
    gallery: [img('1542751370-adc348e3d9aa', 3)],
    techStack: ['C++', 'Lua', 'FiveM'],
    downloads: 6100,
    lastUpdated: '2026-07-11',
    featured: true,
  },
  {
    id: '3',
    slug: 'bundle-ham-redm',
    name: 'Bundle Ham + RedM Menu',
    category: 'bundles',
    categoryLabel: 'Bundles',
    tagline: 'Ham Executor RedM and RedM Menu bundled together.',
    description:
      'The complete RedM modding bundle. Get Ham Executor RedM and RedM Menu together and save. Built specifically for RedM with full RDR2 support.',
    features: [
      'Ham Executor RedM full license',
      'RedM Menu full license',
      'Save 25% vs buying separately',
      'Lifetime updates for both',
      'Single dashboard download',
      'Priority support',
    ],
    price: 21.99,
    originalPrice: 43.98,
    rating: 4.7,
    reviewCount: 134,
    badge: 'new',
    thumbnail: img('1547147834-90ef4a2b67c0', 5),
    gallery: [img('1547147834-90ef4a2b67c0', 5), img('1555066931-cf60f3a44e88', 6)],
    techStack: ['C++', 'Lua', 'RedM'],
    downloads: 3400,
    lastUpdated: '2026-07-10',
  },
  {
    id: '4',
    slug: 'ham-spoofer',
    name: 'Ham Spoofer',
    category: 'tools',
    categoryLabel: 'Tools',
    tagline: 'A reliable hardware ID spoofer to bypass FiveM and RedM bans.',
    description:
      'Ham Spoofer is a reliable hardware ID spoofer that changes your serial numbers to bypass FiveM and RedM bans. Supports all major hardware components and is regularly updated to counter new detections.',
    features: [
      'Spoofs all hardware IDs',
      'Bypasses FiveM and RedM bans',
      'Supports all motherboards and drives',
      'Regularly updated against detections',
      'One-click spoof and restore',
      'Lifetime license',
    ],
    price: 8.99,
    originalPrice: 19.99,
    rating: 4.6,
    reviewCount: 512,
    badge: 'sale',
    thumbnail: '/images/products/682121.webp',
    gallery: ['/images/products/682121.webp'],
    techStack: ['C++', 'Kernel'],
    downloads: 15800,
    lastUpdated: '2026-07-09',
  },
  {
    id: '5',
    slug: 'fivem-roottool',
    name: 'FiveM RootTool',
    category: 'tools',
    categoryLabel: 'Tools',
    tagline: 'An advanced root-level tool for FiveM server administration.',
    description:
      'FiveM RootTool provides advanced root-level access to your FiveM client, allowing deep configuration, debug features, and server-side inspection. A must-have for serious developers and server owners.',
    features: [
      'Root-level client access',
      'Advanced debug and inspection tools',
      'Server-side configuration options',
      'Real-time resource monitoring',
      'Clean, intuitive UI',
      'Lifetime updates',
    ],
    price: 5.00,
    rating: 4.7,
    reviewCount: 189,
    badge: 'new',
    thumbnail: img('1550751827-4bd374c3a584', 8),
    gallery: [img('1550751827-4bd374c3a584', 8)],
    techStack: ['C++', 'Lua', 'FiveM'],
    downloads: 4200,
    lastUpdated: '2026-07-08',
  },
  {
    id: '6',
    slug: 'fivem-ready-accounts',
    name: 'FiveM Ready Accounts',
    category: 'accounts',
    categoryLabel: 'Accounts',
    tagline: 'Verified accounts ready to join whitelisted servers.',
    description:
      'Pre-verified FiveM accounts with linked Discord, clean ban history, and ready to join whitelisted servers. Each account comes with a guarantee of no prior bans and full email access.',
    features: [
      'Verified and ready to play',
      'Linked Discord account included',
      'Clean ban history guaranteed',
      'Full email access included',
      'Instant delivery after purchase',
      '30-day replacement warranty',
    ],
    price: 2.16,
    rating: 4.9,
    reviewCount: 643,
    badge: 'best-seller',
    thumbnail: '/images/products/827376.webp',
    gallery: ['/images/products/827376.webp'],
    techStack: ['FiveM', 'Discord'],
    downloads: 18900,
    lastUpdated: '2026-07-12',
    featured: true,
  },
  {
    id: '7',
    slug: 'discord-accounts',
    name: 'Discord Accounts',
    category: 'accounts',
    categoryLabel: 'Accounts',
    tagline: 'Aged Discord accounts with email access.',
    description:
      'Aged Discord accounts perfect for server verification, community management, or boosting. Available in multiple age ranges. Comes with full email access and a clean history.',
    features: [
      'Aged accounts (2018-2023)',
      'Full email access',
      'Clean history, no bans',
      'Can join and boost servers',
      'Instant delivery',
      '7-day warranty',
    ],
    price: 0.50,
    rating: 4.6,
    reviewCount: 378,
    badge: 'popular',
    thumbnail: '/images/products/827374.webp',
    gallery: ['/images/products/827374.webp'],
    techStack: ['Discord'],
    downloads: 12400,
    lastUpdated: '2026-07-12',
  },
  {
    id: '8',
    slug: 'steam-accounts',
    name: 'Steam Accounts',
    category: 'accounts',
    categoryLabel: 'Accounts',
    tagline: 'Aged Steam accounts with games and prime status.',
    description:
      'Premium aged Steam accounts with various game libraries. From budget starter accounts to loaded libraries with 100+ games. All accounts come with clean VAC history and full email access.',
    features: [
      'Multiple game library options',
      'Prime CS2 status available',
      'Clean VAC history',
      'Aged 3-8+ years',
      'Full email access',
      'Instant delivery',
    ],
    price: 0.10,
    rating: 4.7,
    reviewCount: 289,
    thumbnail: '/images/products/827375.webp',
    gallery: ['/images/products/827375.webp'],
    techStack: ['Steam'],
    downloads: 8200,
    lastUpdated: '2026-07-10',
  },
  {
    id: '9',
    slug: 'redm-ready-accounts',
    name: 'RedM Ready Accounts',
    category: 'accounts',
    categoryLabel: 'Accounts',
    tagline: 'Verified accounts ready for RedM servers.',
    description:
      'Pre-verified RedM accounts with clean ban history, ready to join whitelisted RedM servers. Full email access included with a 30-day replacement warranty.',
    features: [
      'Verified for RedM',
      'Clean ban history',
      'Full email access',
      'Ready for whitelisted servers',
      'Instant delivery',
      '30-day replacement warranty',
    ],
    price: 4.00,
    originalPrice: 9.99,
    rating: 4.8,
    reviewCount: 167,
    badge: 'sale',
    thumbnail: '/images/products/1012122.webp',
    gallery: ['/images/products/1012122.webp'],
    techStack: ['RedM', 'Discord'],
    downloads: 5600,
    lastUpdated: '2026-07-11',
  },
  {
    id: '10',
    slug: 'ham-executor',
    name: 'Ham Executor',
    category: 'menus',
    categoryLabel: 'Mod Menus',
    tagline: 'A lightweight Lua executor for FiveM and Roblox.',
    description:
      'Ham Executor is a lightweight, powerful Lua executor supporting both FiveM and Roblox. Features include a multi-tab code editor, script hub, auto-execute, and a clean UI built on Monaco.',
    features: [
      'Multi-tab Lua code editor',
      'Built-in script hub included',
      'Auto-execute on join',
      'FiveM and Roblox support',
      'Clean, customizable UI',
      'Monaco-based editor',
    ],
    price: 11.99,
    rating: 4.6,
    reviewCount: 892,
    badge: 'popular',
    thumbnail: '/images/products/11.webp',
    gallery: ['/images/products/11.webp'],
    techStack: ['C++', 'Lua', 'Monaco'],
    downloads: 24100,
    lastUpdated: '2026-07-10',
    featured: true,
  },
  {
    id: '11',
    slug: 'ham-executor-redm',
    name: 'Ham Executor RedM',
    category: 'menus',
    categoryLabel: 'Mod Menus',
    tagline: 'A lightweight Lua executor built specifically for RedM.',
    description:
      'Ham Executor RedM is the RedM-focused version of our popular executor. It features full RDR2 support, a built-in script hub with RedM-specific tools, and the same clean Monaco-based editor.',
    features: [
      'Full RedM / RDR2 support',
      'Multi-tab Lua code editor',
      'RedM script hub',
      'Auto-execute on join',
      'Clean, customizable UI',
      'Monaco-based editor',
    ],
    price: 13.99,
    rating: 4.5,
    reviewCount: 334,
    thumbnail: img('1555066931-cf60f3a44e88', 14),
    gallery: [img('1555066931-cf60f3a44e88', 14)],
    techStack: ['C++', 'Lua', 'RedM'],
    downloads: 7800,
    lastUpdated: '2026-07-09',
  },
  {
    id: '12',
    slug: 'vanity-menu',
    name: 'Vanity Menu',
    category: 'menus',
    categoryLabel: 'Mod Menus',
    tagline: 'A premium FiveM modding menu with a sleek, intuitive UI.',
    description:
      'Vanity is a premium FiveM modding menu with an elegant UI, powerful protection bypasses, and a rich feature set including spawn options, player management, and visual enhancements.',
    features: [
      'Sleek, intuitive UI',
      'Powerful protection bypasses',
      'Spawn vehicles, objects, and peds',
      'Player management and teleportation',
      'Visual enhancements (ESP, tracers)',
      'Regular updates and community',
    ],
    price: 11.99,
    rating: 4.8,
    reviewCount: 724,
    badge: 'best-seller',
    thumbnail: '/images/products/681945.webp',
    gallery: ['/images/products/681945.webp'],
    techStack: ['C++', 'Lua', 'FiveM'],
    downloads: 18200,
    lastUpdated: '2026-07-12',
    featured: true,
  },
  {
    id: '13',
    slug: 'redm-menu',
    name: 'RedM Menu',
    category: 'menus',
    categoryLabel: 'Mod Menus',
    tagline: 'A premium modding menu built for RedM and RDR2.',
    description:
      'RedM Menu is a premium modding menu designed specifically for RedM. It features period-appropriate UI styling, full RDR2 entity spawning, player management, and visual tools tailored for the Old West.',
    features: [
      'Built for RedM / RDR2',
      'Period-appropriate UI styling',
      'Full entity spawning',
      'Player management and teleportation',
      'Visual enhancements for RDR2',
      'Regular updates',
    ],
    price: 13.99,
    rating: 4.7,
    reviewCount: 256,
    thumbnail: img('1547147834-90ef4a2b67c0', 16),
    gallery: [img('1547147834-90ef4a2b67c0', 16)],
    techStack: ['C++', 'Lua', 'RedM'],
    downloads: 6400,
    lastUpdated: '2026-07-08',
  },
  {
    id: '14',
    slug: 'cryptic-menu',
    name: 'Cryptic Menu',
    category: 'menus',
    categoryLabel: 'Mod Menus',
    tagline: 'An advanced menu with deep customization and scripting support.',
    description:
      'Cryptic is an advanced FiveM menu featuring deep customization, a built-in Lua scripting engine, protection against common anti-cheats, and a community-driven plugin ecosystem.',
    features: [
      'Built-in Lua scripting engine',
      'Deep UI customization',
      'Protection against common anti-cheats',
      'Community plugin ecosystem',
      'Spectator and recording tools',
      'Lifetime updates included',
    ],
    price: 11.99,
    rating: 4.7,
    reviewCount: 589,
    badge: 'new',
    thumbnail: '/images/products/974868_(1).webp',
    gallery: ['/images/products/974868_(1).webp'],
    techStack: ['C++', 'Lua', 'FiveM'],
    downloads: 11200,
    lastUpdated: '2026-07-11',
    featured: true,
  },
  {
    id: '15',
    slug: 'rockstar-activation-codes',
    name: 'Rockstar Activation Codes',
    category: 'codes',
    categoryLabel: 'Activation Codes',
    tagline: 'Legitimate GTA V and RDR2 activation codes for Rockstar Launcher.',
    description:
      'Legitimate, unused activation codes for GTA V and Red Dead Redemption 2 on the Rockstar Games Launcher. Delivered instantly, region-free, and redeemable worldwide. Perfect for FiveM and RedM players.',
    features: [
      'Unused, legitimate codes',
      'Rockstar Launcher activation',
      'Region-free',
      'GTA V and RDR2 available',
      'Instant delivery',
      'Replacement guarantee',
    ],
    price: 0.50,
    rating: 4.9,
    reviewCount: 1124,
    badge: 'best-seller',
    thumbnail: img('1538481199705-c710c9d1001b', 18),
    gallery: [img('1538481199705-c710c9d1001b', 18)],
    techStack: ['Rockstar'],
    downloads: 24800,
    lastUpdated: '2026-07-13',
  },
  {
    id: '16',
    slug: 'nightfall-redm-mod-menu',
    name: 'Nightfall RedM Mod Menu',
    category: 'menus',
    categoryLabel: 'Mod Menus',
    tagline: 'A stealth-focused mod menu for RedM with advanced features.',
    description:
      'Nightfall is a stealth-focused RedM mod menu with advanced anti-detection, a dark elegant UI, full RDR2 entity control, and a comprehensive feature set designed for serious RedM players.',
    features: [
      'Stealth-focused anti-detection',
      'Dark, elegant UI theme',
      'Full RDR2 entity control',
      'Player and world management',
      'Visual and audio enhancements',
      'Lifetime updates',
    ],
    price: 12.00,
    originalPrice: 24.00,
    rating: 4.6,
    reviewCount: 198,
    badge: 'sale',
    thumbnail: img('1547147834-90ef4a2b67c0', 19),
    gallery: [img('1547147834-90ef4a2b67c0', 19)],
    techStack: ['C++', 'Lua', 'RedM'],
    downloads: 4100,
    lastUpdated: '2026-07-07',
  },
  {
    id: '17',
    slug: 'email-accounts',
    name: 'Email Accounts',
    category: 'email-accounts',
    categoryLabel: 'Email Accounts',
    tagline: 'Aged and verified email accounts for various platforms.',
    description:
      'Aged and verified email accounts from major providers (Gmail, Outlook, Yahoo). Perfect for account creation, verification, and recovery. Each account comes with full access and a clean history.',
    features: [
      'Aged accounts (1-5+ years)',
      'Major providers available',
      'Full access included',
      'Clean history',
      'Instant delivery',
      '7-day warranty',
    ],
    price: 2.03,
    rating: 4.5,
    reviewCount: 445,
    badge: 'popular',
    thumbnail: img('1557800636-37499dcae3c7', 20),
    gallery: [img('1557800636-37499dcae3c7', 20)],
    techStack: ['Gmail', 'Outlook'],
    downloads: 15600,
    lastUpdated: '2026-07-12',
  },
  {
    id: '18',
    slug: 'fivem-anti-spoof-bypasser',
    name: 'FiveM Anti-Spoof Bypasser',
    category: 'tools',
    categoryLabel: 'Tools',
    tagline: 'Bypass FiveM anti-spoof detection systems.',
    description:
      'FiveM Anti-Spoof Bypasser is a specialized tool that bypasses FiveM anti-spoof detection systems, allowing spoofed hardware IDs to pass server-side checks. Regularly updated against new detection methods.',
    features: [
      'Bypasses anti-spoof detection',
      'Works with all major spoofers',
      'Regularly updated',
      'One-click bypass',
      'Clean, simple UI',
      'Lifetime license',
    ],
    price: 5.00,
    rating: 4.4,
    reviewCount: 267,
    thumbnail: img('1550751827-4bd374c3a584', 21),
    gallery: [img('1550751827-4bd374c3a584', 21)],
    techStack: ['C++', 'FiveM'],
    downloads: 8900,
    lastUpdated: '2026-07-06',
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    author: 'Ghost',
    avatar: '',
    rating: 5,
    date: '2026-07-02',
    comment: 'Best bundle deal on the market. Ham and Vanity work flawlessly together. Worth every cent.',
    server: 'Liberty City RP',
  },
  {
    id: 'r2',
    productId: '12',
    author: 'Frost',
    avatar: '',
    rating: 5,
    date: '2026-06-28',
    comment: 'Vanity Menu is clean. UI is buttery smooth and the protection bypasses actually work.',
    server: 'Los Santos Stories',
  },
  {
    id: 'r3',
    productId: '10',
    author: 'Vex',
    avatar: '',
    rating: 5,
    date: '2026-07-05',
    comment: 'Ham Executor is lightweight and fast. Script hub has everything I need. Highly recommend.',
    server: 'Vortex RP',
  },
  {
    id: 'r4',
    productId: '6',
    author: 'Kairo',
    avatar: '',
    rating: 5,
    date: '2026-07-01',
    comment: 'Got my FiveM account instantly. Clean, verified, and working perfectly. Great service.',
    server: 'Apex Gaming',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    author: 'Ghost',
    role: 'Owner, Liberty City RP (400+ players)',
    avatar: '',
    content:
      'We switched our entire server to Nexus Dev products 8 months ago. The quality, optimization, and support are unmatched. Our player count doubled because the gameplay felt premium.',
    rating: 5,
  },
  {
    id: 't2',
    author: 'Frost',
    role: 'Developer, Los Santos Stories',
    avatar: '',
    content:
      'The code quality is exceptional. Clean, documented, and easy to extend. Nexus Dev sets the standard for what FiveM tools should be.',
    rating: 5,
  },
  {
    id: 't3',
    author: 'Vex',
    role: 'Owner, Vortex RP',
    avatar: '',
    content:
      'Ham Spoofer paid for itself in a week. We went from daily ban issues to zero. The support team is responsive and the product just works.',
    rating: 5,
  },
  {
    id: 't4',
    author: 'Kairo',
    role: 'Community Manager, RedM Frontier',
    avatar: '',
    content:
      'The RedM tools are beautifully designed and fit the era perfectly. Our players constantly compliment the immersion. Nexus Dev is the only place we buy from now.',
    rating: 5,
  },
  {
    id: 't5',
    author: 'Ryze',
    role: 'Owner, Apex Gaming Network',
    avatar: '',
    content:
      'I have spent over €2,000 here and never been disappointed. The lifetime updates and the download center make managing my library effortless.',
    rating: 5,
  },
  {
    id: 't6',
    author: 'Ace',
    role: 'Developer, Sunset RP',
    avatar: '',
    content:
      'The documentation is some of the best I have seen. Every tool comes with clear installation guides, config explanations, and video tutorials.',
    rating: 5,
  },
  {
    id: 't7',
    author: 'Volt',
    role: 'Owner, Neon City RP',
    avatar: '',
    content:
      'Cryptic Menu is on another level. The scripting engine is powerful and the community plugins are great. Best menu I have ever used.',
    rating: 5,
  },
  {
    id: 't8',
    author: 'Reaper',
    role: 'Admin, Crystal RP',
    avatar: '',
    content:
      'FiveM Ready Accounts are exactly as described. Instant delivery, clean history, no issues. My go-to for server staffing.',
    rating: 5,
  },
];

export const faqs = [
  {
    question: 'How do I receive my products after purchase?',
    answer:
      'All purchases are handled through our official Discord server. After joining and opening a support ticket, our staff will process your order and deliver your products directly, including download links, license keys, and installation guides.',
  },
  {
    question: 'Do your menus and tools come with lifetime updates?',
    answer:
      'Yes. All menus and tools include lifetime updates for the product you purchased. When we release a new version, you will receive it directly through Discord or your dashboard.',
  },
  {
    question: 'Are the accounts and codes guaranteed?',
    answer:
      'Absolutely. All accounts and activation codes come with a replacement warranty ranging from 7 to 30 days depending on the product. If you encounter any issue within the warranty period, contact support for a free replacement.',
  },
  {
    question: 'Do your tools work on the latest FiveM and RedM versions?',
    answer:
      'Yes. All our tools are regularly updated to work with the latest versions of FiveM and RedM. Each product page lists the current supported version, and updates are delivered through your dashboard.',
  },
  {
    question: 'Can I get a refund if a tool does not work?',
    answer:
      'We offer a 7-day money-back guarantee on tools if the issue cannot be resolved by our support team on Discord. Due to the nature of digital products, accounts and activation codes are non-refundable once delivered, but are covered by our replacement warranty.',
  },
  {
    question: 'How does licensing work?',
    answer:
      'Each tool purchase includes a single-user license. You can manage and transfer your licenses from the License Management page in your dashboard. Multi-user licenses are available on request via Discord.',
  },
  {
    question: 'Is my purchase secure?',
    answer:
      'Absolutely. All purchases are processed manually by our staff through our Discord server. We never ask for sensitive billing information on the website. Your transaction is handled securely and personally by our team.',
  },
  {
    question: 'Do you offer bundles or discounts?',
    answer:
      'Yes! We offer curated bundles that save you up to 25% compared to buying products individually. We also run seasonal sales and offer coupon codes for returning customers.',
  },
];

export const trustedServers = [
  'Liberty City RP',
  'Los Santos Stories',
  'Vortex RP',
  'Apex Gaming',
  'RedM Frontier',
  'Sunset RP',
  'Crystal RP',
  'Neon City',
];

export const stats = [
  { label: 'Happy Customers', value: 240, suffix: '+' },
  { label: 'Products Sold', value: 580, suffix: '+' },
  { label: 'Discord Members', value: 1200, suffix: '+' },
  { label: 'Average Rating', value: 4.9, suffix: '/5', decimals: 1 },
];
